site_name: 化学与生命资源学院 2025迎新
site_url: https://lab.guyue.me/ruc/
site_description: 信息汇总
repo_name: CLR_freshman
repo_url: https://github.com/Guyue2203/CLR_freshman
edit_uri: tree/master/docs
copyright: Copyright &copy; 2025 Guyue

theme: 
  name: 'material'
  language: 'zh'
  icon: 
    logo: material/notebook-outline
  custom_dir: overrides
  favicon: images/icon.png
  features:
    - content.code.annotate
    - navigation.tracking
    # - navigation.tabs
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - search.highlight
    - search.suggest
  font: false
  palette:
    - scheme: default

extra:
  analytics:
    provider: custom
    property: G-G594CHT348

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - https://cdn.tonycrane.cc/utils/katex.min.css
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - https://cdn.tonycrane.cc/turing2022/css/tasklist.css
  - https://cdn.tonycrane.cc/turing2022/css/card.css
  # - https://cdn.tonycrane.cc/turing2022/css/custom.css
  - css/custom.css

extra_javascript:
  - https://cdn.tonycrane.cc/utils/katex.min.js
  - https://cdn.tonycrane.cc/turing2022/js/katex.js
  # js/toc.js    # this is in template 'base.html'
  # js/scheme.js # this is in template 'base.html'

plugins:
  - search
  - heti:
      extra_skipped_class:
        - arithmatex
  - statistics

nav:
  - 主页: index.md
  - 写在前面的话: preface.md
  - 新生防诈骗指南: anti-fraud.md 
  - 入学英语考试: english-test.md
  - 校内校园网连接指南: web.md
  - 校外连接内部网络: vpn.md
  - 校园卡服务: card.md
  - 校园生活指南: living.md
  - 选课指南: courses.md
  - 课程学习建议: study.md
  - 体育设施: sports.md
  - 学分绩点: grade.md
  - 辅修事项: minor.md
  - 转专业: change-of-major.md
  - 推免: recommend.md
  - 工具推荐: tools.md

  
